/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.LecturerBUS;
import DAL.LecturerDAL;
import DTO.LecturerDTO;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.time.LocalDateTime;
import java.util.Calendar;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QuanLyGiangVienPanel extends javax.swing.JPanel {
    private LecturerBUS lecBus;
    /**
     * Creates new form QuanLyGiangVienPanel
     */
    public QuanLyGiangVienPanel() {
        initComponents();
        lecBus=new LecturerBUS(new LecturerDAL());
        setTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfTen = new javax.swing.JTextField();
        tfHo = new javax.swing.JTextField();
        btThem = new javax.swing.JButton();
        btHuy = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        dcNgayThue = new com.toedter.calendar.JDateChooser();
        tfTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSach = new javax.swing.JTable();
        btSearch = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1306, 945));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1252, 125));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Họ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Ngày thuê");

        tfTen.setBackground(new java.awt.Color(184, 178, 178));
        tfTen.setName("tfHo"); // NOI18N
        tfTen.setPreferredSize(new java.awt.Dimension(270, 40));

        tfHo.setBackground(new java.awt.Color(184, 178, 178));
        tfHo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 16))); // NOI18N
        tfHo.setName("tfHo"); // NOI18N
        tfHo.setPreferredSize(new java.awt.Dimension(270, 40));

        btThem.setBackground(new java.awt.Color(0, 0, 204));
        btThem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btThem.setForeground(new java.awt.Color(255, 255, 255));
        btThem.setText("Thêm");
        btThem.setBorderPainted(false);
        btThem.setName("btThem"); // NOI18N
        btThem.setPreferredSize(new java.awt.Dimension(100, 40));
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btHuy.setBackground(new java.awt.Color(255, 0, 0));
        btHuy.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btHuy.setForeground(new java.awt.Color(255, 255, 255));
        btHuy.setText("Hủy");
        btHuy.setBorderPainted(false);
        btHuy.setName("btThem"); // NOI18N
        btHuy.setPreferredSize(new java.awt.Dimension(70, 40));
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(51, 153, 0));
        btSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 255, 255));
        btSua.setText("Sửa");
        btSua.setBorderPainted(false);
        btSua.setName("btThem"); // NOI18N
        btSua.setPreferredSize(new java.awt.Dimension(70, 40));
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(dcNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(tfHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dcNgayThue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tfTimKiem.setBackground(new java.awt.Color(152, 162, 255));
        tfTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfTimKiem.setForeground(new java.awt.Color(102, 102, 102));
        tfTimKiem.setText("Tìm kiếm");
        tfTimKiem.setToolTipText("");
        tfTimKiem.setMinimumSize(new java.awt.Dimension(346, 40));
        tfTimKiem.setPreferredSize(new java.awt.Dimension(346, 40));
        tfTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfTimKiemFocusLost(evt);
            }
        });
        tfTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTimKiemActionPerformed(evt);
            }
        });

        tbDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tbDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Họ", "Tên", "Vị trí", "Ngày thuê", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbDanhSach.setEditingColumn(6);
        tbDanhSach.setPreferredSize(new java.awt.Dimension(1252, 669));
        tbDanhSach.setRowSelectionAllowed(false);
        tbDanhSach.setSelectionBackground(new java.awt.Color(102, 153, 255));
        tbDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDanhSach);

        btSearch.setBackground(new java.awt.Color(152, 162, 255));
        btSearch.setIcon(new ImageIcon("C:\\Users\\DELL\\Desktop\\DoAnJava\\CourseManagement-Embedded\\src\\main\\java\\ICON\\search.png"));
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1306, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void setTable() {
    List<LecturerDTO> listLecturer = lecBus.getAllLecturers();

    DefaultTableModel model = (DefaultTableModel) tbDanhSach.getModel();
    model.setRowCount(0); // Reset bảng bằng cách xóa tất cả các hàng

    ImageIcon trashIcon = new ImageIcon("C:\\Users\\DELL\\Desktop\\DoAnJava\\CourseManagement-Embedded\\src\\main\\java\\ICON\\delete.png");

    // Sử dụng renderer mặc định để hiển thị nút với hình ảnh
    DefaultTableCellRenderer buttonRenderer = new DefaultTableCellRenderer();
    buttonRenderer.setIcon(trashIcon);

    // Đặt renderer cho cột chứa nút
    tbDanhSach.getColumnModel().getColumn(5).setCellRenderer(buttonRenderer);

    for (LecturerDTO lecturer : listLecturer) {
        Object[] rowData = {lecturer.getID(), lecturer.getFirstName(), lecturer.getLastName(), null, lecturer.gethireDate(), " "};
        model.addRow(rowData);
    }

    tbDanhSach.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            int row = tbDanhSach.rowAtPoint(e.getPoint());
            int column = tbDanhSach.columnAtPoint(e.getPoint());
            
            
            tbDanhSach.setRowSelectionInterval(row, row);
            
           
            if (column == 5) {
               int confirm = JOptionPane.showConfirmDialog(QuanLyGiangVienPanel.this, "Bạn có muốn xóa hàng này không?", "Xác nhận xóa", JOptionPane.OK_CANCEL_OPTION);
                if (confirm == JOptionPane.OK_OPTION) {
                lecBus.removeALecturer((int) tbDanhSach.getValueAt(tbDanhSach.getSelectedRow(),0));
                model.removeRow(row);
                }
            }
        }
    });
}
    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:

        int lecturerID = lecBus.getAllLecturers().size()+1 ;
        String surName= tfHo.getText().toString();
        String name= tfTen.getText().toString();

        Date selectedDate = (Date) dcNgayThue.getDate();
        LocalDateTime hireDate =  LocalDateTime.of(selectedDate.getYear()+1900, selectedDate.getMonth(),
            selectedDate.getDate() , selectedDate.getHours(), selectedDate.getMinutes());

        if(surName.equals("")|| name.equals("")  ){
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
        }
        else{
            LecturerDTO lecturer= new LecturerDTO(lecturerID,surName,name, hireDate);

            int result=lecBus.createALecturer(lecturer);
            JOptionPane.showMessageDialog(this, "Test");
            if( result==1){
                JOptionPane.showMessageDialog(this, "Thêm thành công!");}
            else{
                JOptionPane.showMessageDialog(this, "Thêm thất bại!");
            }
        }

        setTable();
    }//GEN-LAST:event_btThemActionPerformed

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:

        btSua.setEnabled(false);
        tfHo.setText("");
        tfTen.setText("");
        Calendar calendar = Calendar.getInstance();
        calendar.set(2000, Calendar.JANUARY, 1); // Đặt ngày: 1/1/2000
        Date defaultDate = (Date) calendar.getTime();
        dcNgayThue.setDate(defaultDate);

        tbDanhSach.clearSelection();
        setTable();
    }//GEN-LAST:event_btHuyActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:

        int lecturerID= (int) tbDanhSach.getValueAt(tbDanhSach.getSelectedRow(), 0);
        LecturerDTO lecDTO= lecBus.getALecturerByID(lecturerID);

        if(lecDTO!=null){
            String lecSurName= tfHo.getText();
            String lecName= tfTen.getText();
            Date selectedDate = (Date) dcNgayThue.getDate();
            LocalDateTime hireDate =  LocalDateTime.of(selectedDate.getYear()+1900, selectedDate.getMonth(),
                selectedDate.getDate() , selectedDate.getHours(), selectedDate.getMinutes());

            lecDTO.setFirstName(lecSurName);
            lecDTO.setLastName(lecName);
            lecDTO.sethireDate(hireDate);
            int result = lecBus.updateALecturer(lecDTO);

            if (result == 1) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                setTable();
            } else {
                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra trong quá trình cập nhật!");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một giảng viên để sửa đổi!");
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void tfTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTimKiemFocusGained
        // TODO add your handling code here:
        if(tfTimKiem.getText().equals("Tìm kiếm")){
            tfTimKiem.setText("");
            tfTimKiem.setForeground(new Color (153,153,153));
        }
    }//GEN-LAST:event_tfTimKiemFocusGained

    private void tfTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfTimKiemFocusLost
        // TODO add your handling code here:
        if(tfTimKiem.getText().equals("")){
            tfTimKiem.setText("Tìm kiếm");
            tfTimKiem.setForeground(new Color (102,102,102));
        }
    }//GEN-LAST:event_tfTimKiemFocusLost

    private void tfTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTimKiemActionPerformed

    private void tbDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhSachMouseClicked
        // TODO add your handling code here:
        tfHo.setText((String)tbDanhSach.getValueAt(tbDanhSach.getSelectedRow(),1));
        tfTen.setText((String)tbDanhSach.getValueAt(tbDanhSach.getSelectedRow(),2));

        LocalDateTime localDateTime= (LocalDateTime)tbDanhSach.getValueAt(tbDanhSach.getSelectedRow(),4);

        Date date = new Date();
        date.setDate(localDateTime.getDayOfMonth());
        date.setMonth(localDateTime.getMonthValue()-1);
        date.setYear(localDateTime.getYear()-1900);

        // Chuyển đổi Calendar thành Date

        // Thiết lập giá trị dateChooserNgayThue với giá trị của date
        dcNgayThue.setDate(date);
    }//GEN-LAST:event_tbDanhSachMouseClicked

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        // TODO add your handling code here:

        List<LecturerDTO> lecturerList= lecBus.getLecturersByName(tfTimKiem.getText());

        DefaultTableModel model = (DefaultTableModel) tbDanhSach.getModel();
        model.setRowCount(0); // Reset bảng bằng cách xóa tất cả các hàng

        ImageIcon trashIcon = new ImageIcon("C:\\Users\\DELL\\Desktop\\DoAnJava\\CourseManagement-Embedded\\src\\main\\java\\ICON\\delete.png");

        // Sử dụng renderer mặc định để hiển thị nút với hình ảnh
        DefaultTableCellRenderer buttonRenderer = new DefaultTableCellRenderer();
        buttonRenderer.setIcon(trashIcon);

        // Đặt renderer cho cột chứa nút
        tbDanhSach.getColumnModel().getColumn(5).setCellRenderer(buttonRenderer);

        for (LecturerDTO lecturer : lecturerList) {
            Object[] rowData = {lecturer.getID(), lecturer.getFirstName(), lecturer.getLastName(), lecturer.getOfficeAssignment().getLocation(), lecturer.gethireDate(), " "};
            model.addRow(rowData);
        }
    }//GEN-LAST:event_btSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private com.toedter.calendar.JDateChooser dcNgayThue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDanhSach;
    private javax.swing.JTextField tfHo;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfTimKiem;
    // End of variables declaration//GEN-END:variables
}
